[package]
name = "ruclif-core"
version = "0.1.0"
edition = "2021"
description = "Ruclif component containing core logic and common/shared entities"
authors = ["Patacode <pata.codegineer@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Patacode/ruclif"
