[package]
name = "ruclif-parser"
version = "0.1.4"
edition = "2021"
description = "Ruclif component to parse CLI arguments"
authors = ["Patacode <pata.codegineer@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Patacode/ruclif"
