[package]
name = "ruclif-parser"
version = "0.1.5"
edition = "2021"
description = "Ruclif component to parse CLI arguments"
authors = ["Patacode <pata.codegineer@gmail.com>"]
repository = "https://github.com/Patacode/ruclif"

license.workspace = true
